// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "next-themes";
// import { RefractiveDock } from "@/components/navbar";
// import { Background } from "@/components/ui/background";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body 
//         className="font-sans {`${GeistSans.variable} ${Geist_Mono.variable} antialiased`}"
//       >
        
//         <ThemeProvider 
//           attribute="class" 
//           defaultTheme="system" 
//           enableSystem 
//           disableTransitionOnChange
//         >
//           <Background className="fixed inset-0 z-0 pointer-events-none" />
//           {/* <RefractiveDock /> */}
          
//           <main className="bg-background text-foreground">
//             {children}
    
//           </main>
//         </ThemeProvider>
//       </body>

//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { Background } from "@/components/ui/background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://marrowstack.dev"),
  title: {
    default: "MarrowStack",
    template: "%s · MarrowStack",
  },
  description:
    "Engineered UI blocks for production apps — polished, reusable, and built for scale.",
  applicationName: "MarrowStack",
  keywords: [
    "MarrowStack",
    "Next.js UI blocks",
    "React components",
    "shadcn",
    "Tailwind CSS",
    "Framer Motion",
    "SaaS blocks",
  ],
  openGraph: {
    title: "MarrowStack",
    description:
      "Engineered UI blocks for production apps — polished, reusable, and built for scale.",
    url: "https://marrowstack.dev",
    siteName: "MarrowStack",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MarrowStack",
    description:
      "Engineered UI blocks for production apps — polished, reusable, and built for scale.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background font-sans text-foreground antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative min-h-screen">
            <Background className="pointer-events-none fixed inset-0 z-0" />
            <div className="relative z-10">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}